using System.Collections.Generic;

public class MyAction
{
    public string Desc {get; set;}
    public int IndexOfGood {get; set;}

    public static List<MyAction> ListOfActions = new List<MyAction>(){
        new MyAction("Помощь бездомным", 1),
        new MyAction("Спасение животного", 2),
        new MyAction("Донорство крови", 1),
        new MyAction("Поддержка чужих начинаний", 1),
        new MyAction("Участие в волонтерской программе", 1),
        new MyAction("Очищение окружающей среды", 1),
        new MyAction("Жертвование денег на благотворительность", 1),
        new MyAction("Вклад в искусство", 3),
        new MyAction("Вклад в общество", 3),
        new MyAction("Обучение других полезным навыкам", 2),
        new MyAction("Поддержка друга в трудной ситуации", 2),
        new MyAction("Честность в сложной ситуации", 2),
        new MyAction("Возврат найденной вещи владельцу", 1),
        new MyAction("Помощь человеку, попавшему в беду", 3),
        new MyAction("Отказ от насилия ради мира", 3),
        new MyAction("Дружелюбие к незнакомцам", 1),
        new MyAction("Вклад в медицину", 3),
        new MyAction("Жертвование во благо друих", 4),
        new MyAction("Проявление терпения в сложной ситуации", 1),
        new MyAction("Уважение природы", 1),
        new MyAction("Создание проекта для помощи людям", 2),
        new MyAction("Жертвование одежды нуждающимся", 1),
        new MyAction("Помощь потерявшемуся ребенку", 2),
        new MyAction("Участие в спасательной операции", 4),
        new MyAction("Защита слабых в конфликте", 3),
        new MyAction("Помощь людям после стихийного бедствия", 3),
        new MyAction("Освещение проблем других людей", 2),
        new MyAction("Приличное поведение в обществе", 1),
        new MyAction("Сочувствие чужой беде", 1),
        new MyAction("Оказание первой медицинской помощи", 4),
        new MyAction("Оказание помощи по мере возможности", 2),
        new MyAction("Положительный пример для подражания", 2),
        new MyAction("Уважение чужого мнения", 2),
        new MyAction("Уход за больным родственником", 2),
        new MyAction("Вдохновление людей на хорошие поступки", 2),
        new MyAction("Вклад в науку", 3),
        new MyAction("Публичная защита прав других", 3),
        new MyAction("Спасение жизни человека", 6),
        new MyAction("Поддержание чистоты", 1),

        new MyAction("Кража", -3),
        new MyAction("Мелкое хищение", -1),
        new MyAction("Разрушение чужого имущества", -2),
        new MyAction("Ложь с целью обмана", -1),
        new MyAction("Жестокое обращение с животным", -4),
        new MyAction("Нападение на человека", -5),
        new MyAction("Каннибализм", -5),
        new MyAction("Участие в мошенничестве", -2),
        new MyAction("Игнорирование чужой просьбы о помощи", -2),
        new MyAction("Нарушение обещаний", -1),
        new MyAction("Предательство", -3),
        new MyAction("Похищение человека", -5),
        new MyAction("Публичное унижение человека", -3),
        new MyAction("Вандализм", -1),
        new MyAction("Саботаж коллективной работы", -1),
        new MyAction("Создание фейковых новостей", -1),
        new MyAction("Использование других в своих целях", -2),
        new MyAction("Принуждение к действиям против воли", -3),
        new MyAction("Насилие", -5),
        new MyAction("Беспечное поведение, ставящее других под угрозу", -2),
        new MyAction("Нарушение авторского права", -1),
        new MyAction("Браконьерство", -2),
        new MyAction("Скрытие налогов", -1),
        new MyAction("Издевательство над человеком", -4),
        new MyAction("Убийство", -6),
        new MyAction("Пренебрежение здоровьем домашних животных", -2),
        new MyAction("Загрязнение окружающей среды", -1),
        new MyAction("Отказ помочь в экстренной ситуации", -3),
        new MyAction("Создание ненужной паники", -1),
        new MyAction("Сокрытие важной информации", -2),
        new MyAction("Угрозы в адрес других людей", -3),
        new MyAction("Преследование человека", -3),
        new MyAction("Запугивание", -3),
        new MyAction("Оскорбления по признакам", -2),
        new MyAction("Подделка документов", -1),
        new MyAction("Пренебрежение воспитанием детей", -4),
        new MyAction("Разжигание ненависти", -3),
        new MyAction("Манипуляции", -3),
        new MyAction("Агрессия", -2),
        new MyAction("Игнорирование моральных принципов ради выгоды", -2),
    };

    public MyAction(string desc, int index){
        Desc = desc;
        IndexOfGood = index;
    }
}

